#[derive(Debug, Clone)]
pub struct CharacterRecord {
    pub character_name: String,
    pub fallback_character_name: Option<String>,
    pub base_hp: Option<f32>,
    pub base_static_hp_regen: Option<f32>,
    pub health_bar_height: Option<f32>,
    pub base_damage: Option<f32>,
    pub base_armor: Option<f32>,
    pub base_spell_block: Option<f32>,
    pub base_move_speed: Option<f32>,
    pub attack_range: Option<f32>,
    pub attack_speed: Option<f32>,
    pub attack_speed_ratio: Option<f32>,
    pub attack_speed_per_level: Option<f32>,
    pub exp_given_on_death: Option<f32>,
    pub gold_given_on_death: Option<f32>,
    pub local_gold_given_on_death: Option<f32>,
    pub global_gold_given_on_death: Option<f32>,
    pub display_name: Option<String>,
    pub hit_fx_scale: Option<f32>,
    pub selection_height: Option<f32>,
    pub selection_radius: Option<f32>,
    pub pathfinding_collision_radius: Option<f32>,
    pub gameplay_collision_radius: Option<f32>,
    pub unit_tags: Option<String>,
    pub description: Option<String>,
}
