use bevy::app::Plugin;
// 所有英雄模块均已编译。`PluginChampions` 仅注册包含完整技能实现的英雄插件，
// 其余英雄可独立选择使用（通过 `app.add_plugins(champion::PluginChampionName)`）。

pub mod aatrox;
pub mod ahri;
pub mod akali;
pub mod akshan;
pub mod alistar;
pub mod amumu;
pub mod anivia;
pub mod annie;
pub mod aphelios;
pub mod ashe;
pub mod aurora;
pub mod bard;
pub mod belveth;
pub mod blitzcrank;
pub mod brand;
pub mod braum;
pub mod briar;
pub mod caitlyn;
pub mod camille;
pub mod cassiopeia;
pub mod darius;
pub mod diana;
pub mod draven;
pub mod ekko;
pub mod evelynn;
pub mod ezreal;
pub mod fiora;
pub mod fizz;
pub mod galio;
pub mod gangplank;
pub mod garen;
pub mod gnar;
pub mod graves;
pub mod hecarim;
pub mod heimerdinger;
pub mod hwei;
pub mod illaoi;
pub mod irelia;
pub mod ivern;
pub mod janna;
pub mod jarvan;
pub mod jax;
pub mod jayce;
pub mod jinx;
pub mod kaisa;
pub mod kalista;
pub mod karma;
pub mod katarina;
pub mod kayle;
pub mod kayn;
pub mod kennen;
pub mod kindred;
pub mod kled;
pub mod leblanc;
pub mod leesin;
pub mod leona;
pub mod lissandra;
pub mod lucian;
pub mod lulu;
pub mod lux;
pub mod malzahar;
pub mod maokai;
pub mod masteryi;
pub mod missfortune;
pub mod mordekaiser;
pub mod morgana;
pub mod nami;
pub mod nasus;
pub mod nautilus;
pub mod neeko;
pub mod nidalee;
pub mod nocturne;
pub mod olaf;
pub mod orianna;
pub mod ornn;
pub mod pantheon;
pub mod pyke;
pub mod qiyana;
pub mod quinn;
pub mod rakan;
pub mod rammus;
pub mod rell;
pub mod renata;
pub mod renekton;
pub mod rengar;
pub mod riven;
pub mod rumble;
pub mod ryze;
pub mod samira;
pub mod sejuani;
pub mod senna;
pub mod seraphine;
pub mod sett;
pub mod shaco;
pub mod shen;
pub mod shyvana;
pub mod singed;
pub mod sion;
pub mod sivir;
pub mod skarner;
pub mod smolder;
pub mod sona;
pub mod soraka;
pub mod swain;
pub mod sylas;
pub mod syndra;
pub mod tahm_kench;
pub mod taliyah;
pub mod talon;
pub mod taric;
pub mod teemo;
pub mod thresh;
pub mod tristana;
pub mod trundle;
pub mod tryndamere;
pub mod twisted_fate;
pub mod twitch;
pub mod urgot;
pub mod volibear;

#[cfg(test)]
mod test_utils;

#[derive(Default)]
pub struct PluginChampions;

impl Plugin for PluginChampions {
    fn build(&self, app: &mut bevy::app::App) {
        app.add_plugins(aatrox::PluginAatrox);
        app.add_plugins(camille::PluginCamille);
        app.add_plugins(darius::PluginDarius);
        app.add_plugins(fiora::PluginFiora);
        app.add_plugins(irelia::PluginIrelia);
        app.add_plugins(mordekaiser::PluginMordekaiser);
        app.add_plugins(riven::PluginRiven);
        app.add_plugins(sett::PluginSett);
        app.add_plugins(volibear::PluginVolibear);
    }
}
