//! 供应商预设数据（移植自 apps/client/src/config/providerPresets.ts）。

pub(super) struct ProviderPreset {
    pub(super) name: &'static str,
    pub(super) preset_type: &'static str,
    pub(super) base_url: &'static str,
    pub(super) api_format: &'static str,
    pub(super) default_models: &'static [&'static str],
    pub(super) website_url: &'static str,
    pub(super) api_key_url: &'static str,
    pub(super) icon: &'static str,
    pub(super) icon_color: &'static str,
}

/// 15 个厂商预设：点选后预填表单（name / baseUrl / apiFormat / 默认模型 / api_key 申请地址）。
pub(super) const PROVIDER_PRESETS: &[ProviderPreset] = &[
    ProviderPreset {
        name: "智谱 BigModel",
        preset_type: "zhipu",
        base_url: "https://open.bigmodel.cn/api/anthropic",
        api_format: "anthropic",
        default_models: &["glm-5.1"],
        website_url: "https://open.bigmodel.cn",
        api_key_url: "https://www.bigmodel.cn/claude-code",
        icon: "zhipu",
        icon_color: "#0F62FE",
    },
    ProviderPreset {
        name: "智谱 z.ai（海外）",
        preset_type: "zhipu_en",
        base_url: "https://api.z.ai/api/anthropic",
        api_format: "anthropic",
        default_models: &["glm-5.1"],
        website_url: "https://z.ai",
        api_key_url: "https://z.ai/subscribe",
        icon: "zhipu",
        icon_color: "#0F62FE",
    },
    ProviderPreset {
        name: "DeepSeek",
        preset_type: "deepseek",
        base_url: "https://api.deepseek.com/anthropic",
        api_format: "anthropic",
        default_models: &["deepseek-v4-pro"],
        website_url: "https://www.deepseek.com",
        api_key_url: "",
        icon: "deepseek",
        icon_color: "#4D6BFE",
    },
    ProviderPreset {
        name: "火山方舟 Agentplan",
        preset_type: "volcengine",
        base_url: "https://ark.cn-beijing.volces.com/api/coding",
        api_format: "anthropic",
        default_models: &["ark-code-latest"],
        website_url: "https://www.volcengine.com/product/ark",
        api_key_url: "",
        icon: "volcengine",
        icon_color: "#1664FF",
    },
    ProviderPreset {
        name: "豆包 Seed",
        preset_type: "doubao",
        base_url: "https://ark.cn-beijing.volces.com/api/compatible",
        api_format: "anthropic",
        default_models: &["doubao-seed-2-1-pro"],
        website_url: "https://www.volcengine.com/product/doubao",
        api_key_url: "",
        icon: "doubao",
        icon_color: "#1664FF",
    },
    ProviderPreset {
        name: "百度千帆 Coding",
        preset_type: "qianfan",
        base_url: "https://qianfan.baidubce.com/anthropic/coding",
        api_format: "anthropic",
        default_models: &["qianfan-code-latest"],
        website_url: "https://cloud.baidu.com/product/qianfan_modelbuilder",
        api_key_url: "",
        icon: "baidu",
        icon_color: "#2932E1",
    },
    ProviderPreset {
        name: "阿里百炼",
        preset_type: "bailian",
        base_url: "https://dashscope.aliyuncs.com/apps/anthropic",
        api_format: "anthropic",
        default_models: &[],
        website_url: "https://bailian.console.aliyun.com",
        api_key_url: "",
        icon: "bailian",
        icon_color: "#624AFF",
    },
    ProviderPreset {
        name: "阿里百炼 For Coding",
        preset_type: "bailian_coding",
        base_url: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
        api_format: "anthropic",
        default_models: &[],
        website_url: "https://bailian.console.aliyun.com",
        api_key_url: "",
        icon: "bailian",
        icon_color: "#624AFF",
    },
    ProviderPreset {
        name: "Kimi",
        preset_type: "kimi",
        base_url: "https://api.moonshot.cn/anthropic",
        api_format: "anthropic",
        default_models: &["kimi-k2.7-code"],
        website_url: "https://platform.moonshot.cn",
        api_key_url: "",
        icon: "kimi",
        icon_color: "#1D1D1F",
    },
    ProviderPreset {
        name: "StepFun",
        preset_type: "stepfun",
        base_url: "https://api.stepfun.com/step_plan",
        api_format: "anthropic",
        default_models: &["step-3.5-flash-2603"],
        website_url: "https://platform.stepfun.com",
        api_key_url: "",
        icon: "stepfun",
        icon_color: "#0066FF",
    },
    ProviderPreset {
        name: "MiniMax",
        preset_type: "minimax",
        base_url: "https://api.minimaxi.com/anthropic",
        api_format: "anthropic",
        default_models: &["MiniMax-M2.7"],
        website_url: "https://platform.minimaxi.com",
        api_key_url: "",
        icon: "minimax",
        icon_color: "#FF6B00",
    },
    ProviderPreset {
        name: "Longcat",
        preset_type: "longcat",
        base_url: "https://api.longcat.chat/anthropic",
        api_format: "anthropic",
        default_models: &["LongCat-Flash-Chat"],
        website_url: "https://longcat.chat",
        api_key_url: "",
        icon: "longcat",
        icon_color: "#7C3AED",
    },
    ProviderPreset {
        name: "百灵 BaiLing",
        preset_type: "bailing",
        base_url: "https://api.tbox.cn/api/anthropic",
        api_format: "anthropic",
        default_models: &["Ling-2.5-1T"],
        website_url: "https://www.tbox.cn",
        api_key_url: "",
        icon: "bailing",
        icon_color: "#1A73E8",
    },
    ProviderPreset {
        name: "小米 MiMo",
        preset_type: "mimo",
        base_url: "https://api.xiaomimimo.com/anthropic",
        api_format: "anthropic",
        default_models: &["mimo-v2.5-pro"],
        website_url: "https://xiaomimimo.com",
        api_key_url: "",
        icon: "mimo",
        icon_color: "#FF6900",
    },
    ProviderPreset {
        name: "KAT-Coder",
        preset_type: "katcoder",
        base_url: "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/claude-code-proxy",
        api_format: "anthropic",
        default_models: &["KAT-Coder-Pro V1"],
        website_url: "https://vanchin.streamlake.ai",
        api_key_url: "",
        icon: "katcoder",
        icon_color: "#111827",
    },
];

/// API 格式下拉选项（取值与 client settings.vue 的 API_FORMATS 一致）。
pub(super) const API_FORMATS: &[(&str, &str)] = &[
    ("anthropic", "Anthropic Messages (/v1/messages)"),
    ("openai_chat", "OpenAI Chat Completions"),
    ("openai_responses", "OpenAI Responses"),
    ("gemini_native", "Gemini Native"),
];

pub(super) fn api_format_label(fmt: &str) -> String {
    API_FORMATS
        .iter()
        .find(|(v, _)| *v == fmt)
        .map(|(_, l)| l.to_string())
        .unwrap_or_else(|| fmt.to_string())
}
