/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue__core_9b8c8f92cf5b04aa___result__Result_____wasm_bindgen_5d1aadfdd29d70b0___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___js_sys_63f53b8bcc268014___Array__web_sys_2345b2f7e6997f0c___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__1_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__2_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__6: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__1__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__11: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___wasm_bindgen_5d1aadfdd29d70b0___JsValue______true__12: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke___core_9b8c8f92cf5b04aa___option__Option_web_sys_2345b2f7e6997f0c___features__gen_Blob__Blob_______true_: (a: number, b: number, c: number) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_5d1aadfdd29d70b0___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
