mod buffs;
mod core;
mod entities;
mod server;
mod ui;

pub use core::*;

use bevy::app::plugin_group;
pub use buffs::*;
pub use entities::*;
pub use server::*;
pub use ui::*;

plugin_group! {
    pub struct PluginCore {
        :PluginDamageReduction,
        :PluginFioraPassive,
        :PluginFioraE,
        :PluginFioraR,
        :PluginRivenPassive,
        :PluginRivenQ,
        :PluginShieldWhite,
        :PluginShieldMagic,

        :PluginBarrack,
        :PluginChampion,
        :PluginCharacter,
        :PluginDebugSphere,
        :PluginMinion,
        :PluginTurret,

        :PluginAatrox,
        :PluginAhri,
        :PluginAkali,
        :PluginAlistar,
        :PluginAmumu,
        :PluginAnivia,
        :PluginAnnie,
        :PluginAshe,
        :PluginAurora,
        :PluginBard,
        :PluginBlitzcrank,
        :PluginBrand,
        :PluginBraum,
        :PluginCaitlyn,
        :PluginCamille,
        :PluginCassiopeia,
        :PluginDiana,
        :PluginDraven,
        :PluginEkko,
        :PluginEvelynn,
        :PluginEzreal,
        :PluginFizz,
        :PluginGalio,
        :PluginGangplank,
        :PluginGraves,
        :PluginHeimerdinger,
        :PluginIllaoi,
        :PluginIvern,
        :PluginJanna,
        :PluginJarvan,
        :PluginJayce,
        :PluginJinx,
        :PluginKaisa,
        :PluginKalista,
        :PluginKarma,
        :PluginKatarina,
        :PluginKayle,
        :PluginKennen,
        :PluginKindred,
        :PluginKled,
        :PluginLeBlanc,
        :PluginLeona,
        :PluginLissandra,
        :PluginLucian,
        :PluginLulu,
        :PluginLux,
        :PluginMalzahar,
        :PluginMaokai,
        :PluginMasterYi,
        :PluginMissFortune,
        :PluginMorgana,
        :PluginNami,
        :PluginNasus,
        :PluginNautilus,
        :PluginNeeko,
        :PluginNidalee,
        :PluginNocturne,
        :PluginOrianna,
        :PluginOrnn,
        :PluginPyke,
        :PluginQiyana,
        :PluginQuinn,
        :PluginRakan,
        :PluginRammus,
        :PluginRell,
        :PluginRenata,
        :PluginRengar,
        :PluginRumble,
        :PluginRyze,
        :PluginSamira,
        :PluginSejuani,
        :PluginSenna,
        :PluginSeraphine,
        :PluginShaco,
        :PluginShen,
        :PluginShyvana,
        :PluginSinged,
        :PluginSion,
        :PluginSivir,
        :PluginSkarner,
        :PluginSmolder,
        :PluginSona,
        :PluginSoraka,
        :PluginSwain,
        :PluginSyndra,
        :PluginTahmKench,
        :PluginTaliyah,
        :PluginTalon,
        :PluginTaric,
        :PluginTeemo,
        :PluginThresh,
        :PluginTristana,
        :PluginTrundle,
        :PluginTryndamere,
        :PluginTwistedFate,
        :PluginTwitch,
        :PluginDarius,
        :PluginFiora,
        :PluginGaren,
        :PluginGnar,
        :PluginHecarim,
        :PluginHwei,
        :PluginIrelia,
        :PluginJax,
        :PluginKayn,
        :PluginLeeSin,
        :PluginOlaf,
        :PluginPantheon,
        :PluginRenekton,
        :PluginRiven,
        :PluginSett,
        :PluginSylas,
        :PluginUrgot,
        :PluginVolibear,

        :PluginAction,
        :PluginAnimation,
        :PluginAttack,
        :PluginAttackAuto,
        :PluginAggro,
        :PluginBase,
        :PluginCamera,
        :PluginController,
        :PluginCooldown,
        :PluginDamage,
        :PluginGame,
        :PluginLife,
        :PluginLifetime,
        :PluginMap,
        :PluginMissile,
        :PluginMovement,
        :PluginNavigaton,
        :PluginParticle,
        :PluginResource,
        :PluginRotate,
        :PluginRun,
        :PluginSkill,
        :PluginSkin,
        :PluginState,
        :PluginUI,
    }
}
